import { Card } from "./types";

export function generateMockCards(): Card[] {
  const now = new Date();
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000);
  const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
  
  const cards: Card[] = [
    // Greetings
    {
      id: "1",
      greek: "Γεια σου",
      translation: "Hello (informal)",
      tags: ["greetings", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "2",
      greek: "Καλημέρα",
      translation: "Good morning",
      tags: ["greetings", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "3",
      greek: "Καληνύχτα",
      translation: "Good night",
      tags: ["greetings", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "4",
      greek: "Ευχαριστώ",
      translation: "Thank you",
      tags: ["greetings", "basics"],
      status: "review",
      reps: 5,
      lapses: 0,
      difficulty: 4.5,
      stability: 3.2,
      lastReview: twoDaysAgo.toISOString(),
      due: yesterday.toISOString(),
      correct: 5,
      incorrect: 0,
    },
    // Food
    {
      id: "5",
      greek: "Ψωμί",
      translation: "Bread",
      tags: ["food", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "6",
      greek: "Νερό",
      translation: "Water",
      tags: ["food", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "7",
      greek: "Κρασί",
      translation: "Wine",
      tags: ["food", "drinks"],
      status: "review",
      reps: 3,
      lapses: 0,
      difficulty: 5.2,
      stability: 2.1,
      lastReview: yesterday.toISOString(),
      due: now.toISOString(),
      correct: 3,
      incorrect: 0,
    },
    {
      id: "8",
      greek: "Τυρί",
      translation: "Cheese",
      tags: ["food"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    // Verbs
    {
      id: "9",
      greek: "Είμαι",
      translation: "I am",
      tags: ["verbs", "basics"],
      status: "review",
      reps: 8,
      lapses: 1,
      difficulty: 6.8,
      stability: 5.5,
      lastReview: twoDaysAgo.toISOString(),
      due: yesterday.toISOString(),
      correct: 7,
      incorrect: 1,
    },
    {
      id: "10",
      greek: "Έχω",
      translation: "I have",
      tags: ["verbs", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "11",
      greek: "Θέλω",
      translation: "I want",
      tags: ["verbs", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "12",
      greek: "Πηγαίνω",
      translation: "I go",
      tags: ["verbs"],
      status: "review",
      reps: 4,
      lapses: 0,
      difficulty: 5.0,
      stability: 2.8,
      lastReview: yesterday.toISOString(),
      due: now.toISOString(),
      correct: 4,
      incorrect: 0,
    },
    // More words
    {
      id: "13",
      greek: "Σπίτι",
      translation: "House",
      tags: ["nouns", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "14",
      greek: "Οικογένεια",
      translation: "Family",
      tags: ["nouns", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "15",
      greek: "Φίλος",
      translation: "Friend",
      tags: ["nouns", "basics"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "16",
      greek: "Αγάπη",
      translation: "Love",
      tags: ["nouns", "emotions"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "17",
      greek: "Χαρά",
      translation: "Joy",
      tags: ["nouns", "emotions"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
    {
      id: "18",
      greek: "Ελευθερία",
      translation: "Freedom",
      tags: ["nouns", "abstract"],
      status: "new",
      reps: 0,
      lapses: 0,
      difficulty: 6.0,
      stability: 0,
      due: now.toISOString(),
      correct: 0,
      incorrect: 0,
    },
  ];

  return cards;
}

